## YAML Template.
---
name: AgentOrange
main: org.bukkit.awesomepants.agentorange.AgentOrange
version: 1.1
website: http://bukkitfun.tumblr.com/
author: AwesomePants
description: >
             Deforestation for the masses.
commands:
  agentorange:
    description: Deforestation!
    usage: |
           Usage -
           /<command> deforest - Deforests a 40x40 cube centered on the user.
           /<command> napalm - Drops napalm onto trees (turns leaves into lava).
           /<command> forestfire - Sets trees on fire (turns leaves into fire).
